civil-wa:
  enabled: false

civil-service:
  java:
    imagePullPolicy: Always
    image: hmctspublic.azurecr.io/civil/service:pr-7241
    keyVaults:
      civil:
        resourceGroup: civil
        secrets:
          - name: civil-idam-client-secret
            alias: idam.client.secret
          - name: microservicekey-civil-service
            alias: idam.s2s-auth.totp_secret
          - name: system-update-user-username
            alias: CIVIL_SYSTEM_UPDATE_USERNAME
          - name: system-update-user-password
            alias: CIVIL_SYSTEM_UPDATE_PASSWORD
          - name: cross-access-user-username
            alias: CIVIL_CROSS_ACCESS_USERNAME
          - name: cross-access-user-password
            alias: CIVIL_CROSS_ACCESS_PASSWORD
          - name: prd-admin-user-username
            alias: CIVIL_PRD_ADMIN_USERNAME
          - name: prd-admin-user-password
            alias: CIVIL_PRD_ADMIN_PASSWORD
          - name: docmosis-api-key
            alias: docmosis.tornado.key
          - name: gov-notify-api-key
            alias: GOV_NOTIFY_API_KEY
          - name: sendgrid-api-key
            alias: SENDGRID_API_KEY
          - name: robotics-notification-sender
            alias: robotics.notification.sender
          - name: robotics-notification-recipient
            alias: robotics.notification.recipient
          - name: launch-darkly-sdk-key-non-prod
            alias: LAUNCH_DARKLY_SDK_KEY
          - name: robotics-notification-multipartyrecipient
            alias: robotics.notification.multipartyrecipient
          - name: robotics-notification-recipient-spec
            alias: robotics.notification.specRecipient
          - name: robotics-notification-recipient-lipj
            alias: robotics.notification.lipJRecipient
          - name: ordnance-survey-api-key
            alias: OS_POSTCODE_LOOKUP_API_KEY
          - name: notification-caseworker-spec-receiver
            alias: notification.caseworker.spec.receiver
          - name: mediation-notification-sender
            alias: mediation.emails.sender
          - name: mediation-notification-recipient
            alias: mediation.emails.recipient
          - name: mediation-json-notification-recipient
            alias: mediation.emails.jsonRecipient
          - name: hmc-servicebus-shared-access-key-tf
            alias: HMC_HEARINGS_TOPIC_ACCESS_KEY
          - name: ccd-shared-servicebus-connection-string
            alias: CCD_EVENTS_TOPIC_CONNECTION_STRING
    environment:
      LAUNCH_DARKLY_ENV: aat
      EM_CCD_ORCHESTRATOR_URL: http://${SERVICE_NAME}-em-ccdorc
      CASE_DOCUMENT_AM_URL: http://${SERVICE_NAME}-cdam
      OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-aat2.internal:8443/openam/oauth2/realms/root/realms/hmcts
      SERVICE_REQUEST_UPDATE: https://${SERVICE_NAME}.preview.platform.hmcts.net/service-request-update
      SERVICE_REQUEST_UPDATE_CLAIM_ISSUED: https://${SERVICE_NAME}.preview.platform.hmcts.net/service-request-update-claim-issued
      HMC_HEARINGS_SUBSCRIPTION_ENABLED: false
      CMC_DB_PASSWORD: "{{ .Values.postgresql.auth.postgresPassword}}"
      COURT_LOCATION_WA_DMN_ENABLED: true
      ROLE_ASSIGNMENT_URL: http://${SERVICE_NAME}-am-role-assignment-service
      CCD_EVENTS_TOPIC_NAME: ${SERVICE_NAME}-asb-ccd-case-events
      CCD_EVENTS_SUBSCRIPTION_NAME: ${SERVICE_NAME}-asb-ccd-case-events
      CCD_EVENTS_SERVICE_BUS_CONCURRENT_SESSIONS: 1
      CCD_EVENTS_SUBSCRIPTION_ENABLED: false
      CCD_EVENTS_SUBSCRIPTION_RETRY_DURATION: 60
      RD_PROFESSIONAL_API_URL: http://${SERVICE_NAME}-wiremock
      DOCMOSIS_TORNADO_URL: http://${SERVICE_NAME}-wiremock
    #      CMC_DB_HOST: civil-preview.postgres.database.azure.com
#      CMC_DB_CONNECTION_OPTIONS: "?stringtype=unspecified&reWriteBatchedInserts=true&sslmode=require"
#      CMC_DB_USERNAME: hmcts
#      CMC_DB_NAME: "pr-${CHANGE_ID}-cmc"
    secrets:
      CMC_DB_PASSWORD:
        secretRef: postgres
        key: PASSWORD
        disabled: true
      CCD_EVENTS_TOPIC_CONNECTION_STRING:
        secretRef: civil-sb-preview
        key: connectionString
    postgresql:
      enabled: true
      releaseNameOverride: ${SERVICE_NAME}-postgresql
      auth:
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        database: cft_task_db
        postgresPassword: ${POSTGRES_PASSWORD}
      primary:
        persistence:
          enabled: false
        extraEnvVars:
          - name: POSTGRESQL_WAL_LEVEL
            value: "logical"
          - name: POSTGRESQL_MAX_CONNECTIONS
            value: "400"
        extendedConfiguration: |
            max_connections = 400
            shared_buffers = 512MB
        resources:
          requests:
            cpu: 500m
            memory: 2048Mi
        podAnnotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        initdb:
          user: postgres
          password: ${POSTGRES_PASSWORD}
          scripts:
            01_init_civil.sql: |
              CREATE DATABASE cmc WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
              CREATE DATABASE "data-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
              CREATE DATABASE "definition-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
              CREATE DATABASE "camunda" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
              CREATE DATABASE "role_assignment" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
              CREATE DATABASE "ts_translation_service" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
              CREATE DATABASE "emstitch" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
            02_init_wa.sql: |
              CREATE DATABASE "wa-task-management-api" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
              CREATE DATABASE "wa-case-event-handler" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
              CREATE DATABASE "wa_workflow_api" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
              CREATE DATABASE "cft_task_db_replica" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
idam-pr:
  redirect_uris:
    XUI:
      - https://xui-${SERVICE_FQDN}/oauth2/callback
    CCD Admin:
      - http://${SERVICE_NAME}-ccd-admin-web/oauth2redirect

aac-manage-case-assignment:
  java:
    ingressHost: manage-case-assignment-${SERVICE_NAME}.preview.platform.hmcts.net

xui-webapp:
  nodejs:
    ingressHost: xui-${SERVICE_FQDN}
    environment:
      FEATURE_ACCESS_MANAGEMENT_ENABLED: true
      SERVICES_DOCUMENTS_API_V2: http://${SERVICE_NAME}-cdam
      SERVICES_WORK_ALLOCATION_TASK_API: http://{{ .Release.Name }}-wa-task-management-api
      SERVICES_WA_WORKFLOW_API_URL: http://wa-workflow-api-${SERVICE_FQDN}
      SERVICES_TRANSLATION_API_URL: http://${SERVICE_NAME}-translation-service
      SERVICES_ROLE_ASSIGNMENT_API: https://am-role-assignment-${SERVICE_FQDN}
ccd:
  ccd:
    ras:
      enabled: true
  global:
    ccdStitchUrl: http://${SERVICE_NAME}-emstitch
    postgresUsername: ${POSTGRES_USER}
    postgresPassword: ${POSTGRES_PASSWORD}
    postgresSecret: postgres
#    postgresHostname: civil-preview.postgres.database.azure.com
#    databaseNamePrefix: "pr-${CHANGE_ID}-"
  ccd-api-gateway-web:
    nodejs:
      ingressHost: gateway-${SERVICE_FQDN}
  ccd-data-store-api:
    java:
      environment:
        CASE_DOCUMENT_AM_API_ATTACH_DOCUMENT_ENABLED: true
        CASE_DOCUMENT_AM_URL: http://${SERVICE_NAME}-cdam
        OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
        CCD_S2S_AUTHORISED_SERVICES_CASE_USER_ROLES: civil_service,aac_manage_case_assignment
        DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_gw,ccd_ps,bulk_scan_orchestrator,ccpay_bubble,ctsc_work_allocation,em_ccd_orchestrator,xui_webapp,civil_service,ccd_case_document_am_api,aac_manage_case_assignment,wa_task_management_api,wa_task_monitor,wa_case_event_handler,wa_workflow_api,civil_general_applications
        DATA_STORE_DB_OPTIONS: "?stringtype=unspecified"
        DATA_STORE_DB_PASSWORD: ${POSTGRES_PASSWORD}
        DATA_STORE_DEFAULT_LOG_LEVEL: INFO
        CCD_MULTIPARTY_LOG_LEVEL: INFO
        CASE_DATA_ISSUE_LOG_LEVEL: INFO
        UPLOAD_TIMESTAMP_FEATURED_CASE_TYPES: CIVIL, GENERALAPPLICATION
        CCD_MULTIPARTY_CASE_TYPES: CIVIL
        CCD_MULTIPARTY_EVENTS: DEFENDANT_RESPONSE,ACKNOWLEDGE_CLAIM,CLAIMANT_RESPONSE,queryManagementRaiseQuery,queryManagementRespondQuery
        ROLE_ASSIGNMENT_URL: http://${SERVICE_NAME}-am-role-assignment-service
      ingressHost: ccd-data-store-api-${SERVICE_FQDN}
      secrets:
        DATA_STORE_DB_PASSWORD:
          secretRef: "{{ .Values.global.postgresSecret }}"
          key: PASSWORD
          disabled: true
  am-role-assignment-service:
    java:
      releaseNameOverride: ${SERVICE_NAME}-am-role-assignment-service
      imagePullPolicy: Always
      image: hmctspublic.azurecr.io/am/role-assignment-service:latest
      ingressHost: am-role-assignment-${SERVICE_FQDN}
      environment:
        RELEASE_REVISION: "{{ .Release.Revision }}"
        ROLE_ASSIGNMENT_DB_PASSWORD: ${POSTGRES_PASSWORD}
        ROLE_ASSIGNMENT_DB_OPTIONS: "?stringtype=unspecified"
      keyVaults:
        am:
          secrets:
            - name: role-assignment-service-LD-SDK-KEY
              alias: LD_SDK_KEY
  ccd-definition-store-api:
    java:
      ingressHost: ccd-definition-store-${SERVICE_FQDN}
      environment:
        DEFINITION_STORE_DB_OPTIONS: "?stringtype=unspecified"
        DEFINITION_STORE_DB_PASSWORD: ${POSTGRES_PASSWORD}
      secrets:
        DEFINITION_STORE_DB_PASSWORD:
          secretRef: "{{ .Values.global.postgresSecret }}"
          key: PASSWORD
          disabled: true
  ccd-user-profile-api:
    java:
      environment:
        USER_PROFILE_DB_OPTIONS: "?stringtype=unspecified"
        USER_PROFILE_DB_PASSWORD: ${POSTGRES_PASSWORD}
      secrets:
        USER_PROFILE_DB_PASSWORD:
          secretRef: "{{ .Values.global.postgresSecret }}"
          key: PASSWORD
          disabled: true

camunda-bpm:
  enabled: true
  java:
    disableKeyVaults: true
    environment:
#      CAMUNDA_DB_HOST: civil-preview.postgres.database.azure.com
#      CAMUNDA_DB_USER_NAME: hmcts
#      CAMUNDA_DB_CONN_OPTIONS: "?stringtype=unspecified&reWriteBatchedInserts=true&sslmode=require"
#      CAMUNDA_DB_NAME: "pr-${CHANGE_ID}-camunda"
      CAMUNDA_DB_PASSWORD: ${POSTGRES_PASSWORD}
      CAMUNDA_DB_USER_NAME: ${POSTGRES_USER}
      TEMP_VAR: false
    secrets:
      CAMUNDA_DB_PASSWORD:
        secretRef: postgres
        key: PASSWORD
        disabled: true

em-ccdorc:
  enabled: true
  java:
    image: hmctspublic.azurecr.io/em/ccdorc:latest
    releaseNameOverride: ${SERVICE_NAME}-em-ccdorc
    ingressHost: em-ccdorc-${SERVICE_FQDN}
    environment:
      IDAM_API_BASE_URI: https://idam-api.aat.platform.hmcts.net
      OPEN_ID_API_BASE_URI: https://idam-web-public.aat.platform.hmcts.net/o
      S2S_BASE_URI: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      EM_STITCHING_API_URL: https://em-stitching-${SERVICE_FQDN}
      DM_STORE_APP_URL: http://dm-store-aat.service.core-compute-aat.internal
      CCD_DATA_API_URL: http://${SERVICE_NAME}-ccd-data-store-api
      CALLBACK_HTTP_SCHEME: https
      CALLBACK_DOMAIN: em-ccdorc-${SERVICE_FQDN}
    keyVaults:
      em-ccdorc:
        resourceGroup: em-ccdorc
        secrets:
          - name: microservicekey-em-ccd-orchestrator
            alias: S2S_KEY
          - name: notification-api-key
            alias: NOTIFICATION_API_KEY

em-stitching:
  enabled: true
  java:
    imagePullPolicy: Always
    releaseNameOverride: ${SERVICE_NAME}-em-stitching
    image: hmctspublic.azurecr.io/em/stitching:latest
    ingressHost: em-stitching-${SERVICE_FQDN}
    environment:
      IDAM_API_BASE_URI: https://idam-api.aat.platform.hmcts.net
      OPEN_ID_API_BASE_URI: https://idam-web-public.aat.platform.hmcts.net/o
      S2S_BASE_URI: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      DM_STORE_APP_URL: http://dm-store-aat.service.core-compute-aat.internal
      CDAM_URL: http://${SERVICE_NAME}-cdam
      SPRING_DATASOURCE_HOST: ${SERVICE_NAME}-postgresql
      SPRING_DATASOURCE_NAME: emstitch
      SPRING_DATASOURCE_OPTIONS: "?ssl=disable"
      SPRING_DATASOURCE_PORT: 5432
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      ENABLE_DB_MIGRATE: true
      RUN_DB_MIGRATION_ON_STARTUP: true
      FLYWAY_POSTGRESQL_TRANSACTIONAL_LOCK: false
      LOGGING_LEVEL_UK_GOV_HMCTS_REFORM_EM: DEBUG
    keyVaults:
      em-stitching:
        resourceGroup: em-stitching
        secrets:
          - name: docmosis-access-key
            alias: DOCMOSIS_ACCESS_KEY
          - name: microservicekey-em-stitching-api
            alias: S2S_KEY

ccd-case-document-am-api:
  enabled: true
  java:
    releaseNameOverride: ${SERVICE_NAME}-cdam
    imagePullPolicy: Always
    image: hmctspublic.azurecr.io/ccd/case-document-am-api:latest
    ingressHost: ccd-case-document-am-api-${SERVICE_FQDN}
    environment:
      IDAM_API_URL: https://idam-api.aat.platform.hmcts.net
      IDAM_OIDC_URL: https://idam-web-public.aat.platform.hmcts.net
      OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-aat.internal:8443/openam/oauth2/hmcts
      S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      DM_STORE_BASE_URL: http://dm-store-aat.service.core-compute-aat.internal
      CCD_DATA_STORE_API_BASE_URL: http://${SERVICE_NAME}-ccd-data-store-api
      CASE_DOCUMENT_AM_API_S2S_SECRET: ${CASE_DOCUMENT_AM_API_S2S_SECRET}
    keyVaults: []

ccd-message-publisher:
  java:
    ingressHost: ccd-message-publisher-${SERVICE_FQDN}
    releaseNameOverride: ${SERVICE_NAME}-ccd-message-publisher
    keyVaults:
      ccd:
        secrets:
          - name: AppInsightsInstrumentationKey
            alias: azure.application-insights.instrumentation-key
    environment:
#      DATA_STORE_DB_HOST: civil-preview.postgres.database.azure.com
#      DATA_STORE_DB_NAME: "pr-${CHANGE_ID}-data-store"
#      DATA_STORE_DB_USERNAME: hmcts
#      DATA_STORE_DB_OPTIONS: "?stringtype=unspecified&reWriteBatchedInserts=true&sslmode=require"
      DATA_STORE_DB_HOST: "{{ .Release.Name }}-postgresql"
      DATA_STORE_DB_NAME: "data-store"
      DATA_STORE_DB_USERNAME: ${POSTGRES_USER}
      DATA_STORE_DB_PASSWORD: ${POSTGRES_PASSWORD}
      DATA_STORE_DB_OPTIONS: "?stringtype=unspecified"
      CCD_CASE_EVENTS_DESTINATION: ${SERVICE_NAME}-asb-ccd-case-events
    secrets:
      SERVICE_BUS_CONNECTION_STRING:
        secretRef: civil-sb-preview
        key: connectionString
      DATA_STORE_DB_PASSWORD:
        secretRef: postgres
        key: PASSWORD
        disabled: true

ccd-events-topic:
  enabled: true

postgresql:
  enabled: false
  flexibleserver: civil-preview
  setup:
    databases:
      - name: "pr-${CHANGE_ID}-data-store"
      - name: "pr-${CHANGE_ID}-definition-store"
      - name: "pr-${CHANGE_ID}-user-profile"
      - name: "pr-${CHANGE_ID}-camunda"
      - name: "pr-${CHANGE_ID}-role-assignment"
      - name: "pr-${CHANGE_ID}-cft_task_db"
      - name: "pr-${CHANGE_ID}-wa-case-event-handler"
      - name: "pr-${CHANGE_ID}-wa_workflow_api"
      - name: "pr-${CHANGE_ID}-cmc"

servicebus:
  enabled: true
  releaseNameOverride: ${SERVICE_NAME}-asb
  resourceGroup: civil-aso-preview-rg
  sbNamespace: civil-servicebus-preview # due to a bug https://github.com/kubernetes-sigs/kustomize/issues/5072 this value is set to civil, when this bug is resolved, the sbNamespace should be changed to the actual name of the Service Bus Namespace (civil-sb-preview)
  setup:
    topics:
      - name: ccd-case-events
        subscriptionNeeded: yes
        requiresSession: true
      - name: crd-topic
        subscriptionNeeded: yes
      - name: jrd-topic
        subscriptionNeeded: yes


wiremock:
  enabled: true
  image: hmctspublic.azurecr.io/imported/wiremock/wiremock
  applicationPort: 8080
  imagePullPolicy: Always
  releaseNameOverride : ${SERVICE_NAME}-wiremock
  verbose: true
  ingressHost: wiremock-${SERVICE_NAME}.preview.platform.hmcts.net
  volumes:
    - name: wiremock-mocks
      configMap:
        name: ${SERVICE_NAME}-wiremock-wm
  volumeMounts:
    - name: wiremock-mocks
      mountPath: /home/wiremock/mappings
      subPath: mappings
