civil-service:
  java:
    image: 'hmctspublic.azurecr.io/civil/service:pr-1856'
    keyVaults:
      civil:
        resourceGroup: civil
        secrets:
          - civil-idam-client-secret
          - microservicekey-civil-service
          - system-update-user-username
          - system-update-user-password
          - cross-access-user-username
          - cross-access-user-password
          - prd-admin-user-username
          - prd-admin-user-password
          - docmosis-api-key
          - gov-notify-api-key
          - sendgrid-api-key
          - robotics-notification-sender
          - robotics-notification-recipient
          - robotics-notification-recipient-spec
          - name: launch-darkly-sdk-key-non-prod
            alias: launch-darkly-sdk-key
          - ordnance-survey-api-key
          - robotics-notification-multipartyrecipient
          - notification-caseworker-spec-receiver
    environment:
      LAUNCH_DARKLY_ENV: ${SERVICE_FQDN}
      OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-aat2.internal:8443/openam/oauth2/realms/root/realms/hmcts
idam-pr:
  redirect_uris:
    XUI:
      - https://xui-${SERVICE_FQDN}/oauth2/callback

civil-general-applications:
  enabled: true
xui-webapp:
  nodejs:
    ingressHost: xui-${SERVICE_FQDN}
ccd:
  ccd-api-gateway-web:
    nodejs:
      ingressHost: gateway-${SERVICE_FQDN}
  ccd-data-store-api:
    java:
      environment:
        OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
        CCD_S2S_AUTHORISED_SERVICES_CASE_USER_ROLES: civil_service,aac_manage_case_assignment
      ingressHost: ccd-data-store-api-${SERVICE_FQDN}
  ccd-definition-store-api:
    java:
      ingressHost: ccd-definition-store-${SERVICE_FQDN}
camunda-bpm:
  java:
    ingressHost: camunda-${SERVICE_FQDN}
