civil-service:
  java:
    image: 'hmctspublic.azurecr.io/civil/service:pr-3193'
    keyVaults:
      civil:
        resourceGroup: civil
        secrets:
          - civil-idam-client-secret
          - microservicekey-civil-service
          - system-update-user-username
          - system-update-user-password
          - cross-access-user-username
          - cross-access-user-password
          - prd-admin-user-username
          - prd-admin-user-password
          - docmosis-api-key
          - gov-notify-api-key
          - sendgrid-api-key
          - robotics-notification-sender
          - robotics-notification-recipient
          - robotics-notification-recipient-spec
          - name: launch-darkly-sdk-key-non-prod
            alias: launch-darkly-sdk-key
          - ordnance-survey-api-key
          - robotics-notification-multipartyrecipient
          - notification-caseworker-spec-receiver
    environment:
      LAUNCH_DARKLY_ENV: ${SERVICE_FQDN}
      OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-aat2.internal:8443/openam/oauth2/realms/root/realms/hmcts
      SERVICE_REQUEST_UPDATE: https://${SERVICE_NAME}.preview.platform.hmcts.net/service-request-update
      SERVICE_REQUEST_UPDATE_CLAIM_ISSUED: https://${SERVICE_NAME}.preview.platform.hmcts.net/service-request-update-claim-issued
      HMC_HEARINGS_SUBSCRIPTION_ENABLED: false
idam-pr:
  redirect_uris:
    XUI:
      - https://xui-${SERVICE_FQDN}/oauth2/callback

aac-manage-case-assignment:
  java:
    ingressHost: manage-case-assignment-${SERVICE_NAME}.preview.platform.hmcts.net

civil-general-applications:
  enabled: true
xui-webapp:
  nodejs:
    ingressHost: xui-${SERVICE_FQDN}
    environment:
      SERVICES_WORK_ALLOCATION_TASK_API: https://wa-task-management-api-${SERVICE_FQDN}
      SERVICES_WA_WORKFLOW_API_URL: http://wa-workflow-api-${SERVICE_FQDN}
ccd:
  ccd-api-gateway-web:
    nodejs:
      ingressHost: gateway-${SERVICE_FQDN}
  ccd-data-store-api:
    java:
      environment:
        OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
        CCD_S2S_AUTHORISED_SERVICES_CASE_USER_ROLES: civil_service,aac_manage_case_assignment
        DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_gw,ccd_ps,bulk_scan_orchestrator,ccpay_bubble,ctsc_work_allocation,em_ccd_orchestrator,xui_webapp,civil_service,ccd_case_document_am_api,aac_manage_case_assignment,wa_task_management_api,wa_task_monitor,wa_case_event_handler,wa_workflow_api,civil_general_applications
      ingressHost: ccd-data-store-api-${SERVICE_FQDN}
  ccd-definition-store-api:
    java:
      ingressHost: ccd-definition-store-${SERVICE_FQDN}

camunda-bpm:
  java:
    ingressHost: camunda-${SERVICE_FQDN}

civil-wa:
  enabled: false
