name: Update README Test Documentation Tables

on:
  push:
    branches:
      - master

jobs:
  generate-readme-tables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Use Node.js 18
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: 24

      - name: Install dependencies
        env:
          YARN_ENABLE_SCRIPTS: "false"
        run: yarn install --frozen-lockfile

      - name: Regenerate documentation JSON
        run: |
          yarn test:generate:e2e-api-data
          yarn test:generate:e2e-ui-data

      - name: Update README UI table
        run: yarn test:readme:e2e-ui-table

      - name: Update README API table
        run: yarn test:readme:e2e-api-table

      - name: Commit and push README updates
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5
        with:
          commit_message: "chore: refresh README test documentation tables"
          branch: master
